---
- name: Update all VMs
  hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: Update all packages
      dnf:
        name: "*"
        state: latest
        
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true
